# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'untitled.ui'
#
# Created by: PyQt5 UI code generator 5.15.7
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(400, 400)
        self.ButtonTea = QtWidgets.QPushButton(Form)
        self.ButtonTea.setGeometry(QtCore.QRect(10, 340, 120, 50))
        self.ButtonTea.setObjectName("ButtonTea")
        self.ButtonCoffe = QtWidgets.QPushButton(Form)
        self.ButtonCoffe.setGeometry(QtCore.QRect(270, 340, 120, 50))
        self.ButtonCoffe.setObjectName("ButtonCoffe")
        self.CoffeText = QtWidgets.QTextEdit(Form)
        self.CoffeText.setGeometry(QtCore.QRect(140, 270, 131, 71))
        self.CoffeText.setObjectName("CoffeText")
        self.TeaText = QtWidgets.QTextEdit(Form)
        self.TeaText.setGeometry(QtCore.QRect(140, 270, 131, 71))
        self.TeaText.setObjectName("TeaText")
        self.label_3 = QtWidgets.QLabel(Form)
        self.label_3.setGeometry(QtCore.QRect(100, 10, 221, 51))
        font = QtGui.QFont()
        font.setPointSize(16)
        self.label_3.setFont(font)
        self.label_3.setAutoFillBackground(False)
        self.label_3.setObjectName("label_3")
        self.label = QtWidgets.QLabel(Form)
        self.label.setGeometry(QtCore.QRect(90, 60, 251, 181))
        self.label.setText("")
        self.label.setPixmap(QtGui.QPixmap("../../Desktop/1.jpg"))
        self.label.setObjectName("label")

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Form"))
        self.ButtonTea.setText(_translate("Form", "Чай"))
        self.ButtonCoffe.setText(_translate("Form", "Кофе"))
        self.CoffeText.setHtml(_translate("Form", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'MS Shell Dlg 2\'; font-size:8.25pt; font-weight:400; font-style:normal;\">\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:10pt;\">Вы выбрали кофе</span></p></body></html>"))
        self.TeaText.setHtml(_translate("Form", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'MS Shell Dlg 2\'; font-size:8.25pt; font-weight:400; font-style:normal;\">\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:10pt;\">Вы выбрали чай</span></p></body></html>"))
        self.label_3.setText(_translate("Form", "CЛОЖНЫЙ ВЫБОР"))
